<?php 
$db_host="localhost"; 
$db_user="root"; 
$db_pass="hgl2000"; 
$db_name="his"; 
$table_patient="his_patient"; 
$table_doctor="his_doctor"; 
$table_medicine="his_medicine"; 
$table_user="his_user"; 
$table_department="his_department"; 
$table_itemlist="his_itemlist"; 
$table_arrange="his_arrange"; 
$table_pilllist="his_pilllist"; 
$table_costlist="his_costlist"; 
$table_disease="his_disease"; 
$table_article="his_article"; 
$table_post="his_post"; 
$table_topic="his_topic"; 
$table_praise="his_praise"; 
$table_settop="his_settop"; 
$table_peach="his_peach"; 
$table_collect="his_collect"; 
$link=mysqli_connect($db_host,$db_user,$db_pass);
mysqli_select_db($link,$db_name); 
?>